#!/usr/bin/env csh

# setup file to store bookmarks
if ( ! "$?CDIRS" ) setenv CDIRS ~/.cdirs
touch $CDIRS

# cshmarks alias
alias l     'source ~/.cshmarks/list'
alias s     'source ~/.cshmarks/save'
alias g     'source ~/.cshmarks/goto'
alias d     'source ~/.cshmarks/delete'

# completion command
complete g 'p/1/`cat $CDIRS | cut -d" " -f1`/'
complete d 'p/1/`cat $CDIRS | cut -d" " -f1`/'
